#!/usr/bin/env ruby
# encoding: utf-8

# Default to production, can be overridden by setting RAILS_ENV
#ENV['RAILS_ENV'] ||= 'production'

require File.expand_path('../../config/boot',  __FILE__)
require 'commands/server'
