default: pdf

pdf: sk_web_bedienungsanleitung.tex
	pdflatex sk_web_bedienungsanleitung.tex

.PHONY: clean
clean:
	-rm sk_web_bedienungsanleitung.aux
	-rm sk_web_bedienungsanleitung.log
	-rm sk_web_bedienungsanleitung.out
	-rm sk_web_bedienungsanleitung.toc
	-rm sk_web_bedienungsanleitung.pdf

